# Generated by Django 5.1.2 on 2025-06-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0005_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='Chat_media/'),
        ),
    ]
